### ISSUE TITLE
KML generated by KADAS fails validation against the specified xmlns

### ISSUE THREAD

**Issue by TxKroar** [kadas-albireo/kadas-albireo2#11]
Hello everyone, 
while attempting to import/parse a KML File generated by KADAS in another application we noticed that there's a minor issue with the generated KML:
Attempting to Validate KML generated by KADAS CI Build for Commit 9ba17c02b4cfb4f8fc171369ae710ba63c4bc256 fails:
![image](https://user-images.githubusercontent.com/63401073/78890562-2a1cba00-7a66-11ea-91b0-10b53d8dfabf.png)
(The KML File in the Screenshot is a pretty printed version of the KML File in the following Archive: 
[test-kml.zip](https://github.com/kadas-albireo/kadas-albireo2/files/4455869/test-kml.zip))

The reason for the validation failure is that the XSD Schema for KML Files uses \<sequence\> Tags for the Child Elements within the \<LineStyle\> Tag and thus the order of the Child elements matters:
![image](https://user-images.githubusercontent.com/63401073/78891074-1756b500-7a67-11ea-8da0-be1de2c4bdfa.png)
![image](https://user-images.githubusercontent.com/63401073/78891080-1b82d280-7a67-11ea-8b58-e93a95c941f6.png)
XSD Schema used by KADAS in KML Files: http://www.opengis.net/kml/2.2
Documentation of the \<sequence\> Tag: https://www.w3schools.com/xml/el_sequence.asp

The XSD Schema for KML indicates that flipping the order of the \<width\> and \<color\> child elements in the \<LineStyle\> and \<PolyStyle\> Tags solves this problem:
![image](https://user-images.githubusercontent.com/63401073/78891539-0fe3db80-7a68-11ea-8465-4cd6ff7f8306.png)

The Issue is probably caused by the following code:
https://github.com/kadas-albireo/kadas-albireo2/blob/9ba17c02b4cfb4f8fc171369ae710ba63c4bc256/kadas/app/kml/kadaskmlexport.cpp#L452

**Comment by manisandro** [comment]
Fixed, thanks!
