### ISSUE TITLE
KML Export: ExtendedData Tag should be right before the MultiGeometry Tag

### ISSUE THREAD

**Issue by TxKroar** [kadas-albireo/kadas-albireo2#15]
Hello,
The KML2.2 Spec requires that the ExtendedData Tag is before the MultiGeometry Tag inside \<Placemark\>\</Placemark>:
![image](https://user-images.githubusercontent.com/63401073/81384584-2c7c3d80-9112-11ea-955a-4a8c50c82b52.png)
In this Extract from the KML2.2 XSD File we see that AbstractFeatureType Comes before AbstractGeometryGroup (AbstractGeometryGroup=MultiGeometry in KML generated by KADAS)
A look at AbstractFeatureType shows that the ExtendedData Tag should be after the Style Tag
![image](https://user-images.githubusercontent.com/63401073/81384370-d909ef80-9111-11ea-852c-637ed7cadd09.png)

In addition to that I forgot to mention in the previous ticket that the fill-Tag and color-Tag inside \<PolyStyle\> should be flipped as well: the KML 2.2 XSD expects the color to be first.

Attached is a pretty printed example of KML generated by the May 5. 2020 CI Build of KADAS and the same KML, but slightly modified so as to pass Validation against the XSD: [KML_examples.zip](https://github.com/kadas-albireo/kadas-albireo2/files/4597778/KML_examples.zip)

In case you want to validate the generated KML yourself, you can easily do so using [XSD Validator](https://github.com/amouat/xsd-validator/blob/master/src/xsdvalidator/validate.java) and the [KML2.2 XSD](https://github.com/kadas-albireo/kadas-albireo2/files/4597797/KML2.2_Schema.zip)

**Comment by manisandro** [comment]
Thanks, should be addressed.
