### ISSUE TITLE
Endless Loop in arcgisportalcatalogprovider

### ISSUE THREAD

**Issue by ltbam** [kadas-albireo/kadas-albireo2#25]
https://github.com/kadas-albireo/kadas-albireo2/blob/1af969c0dac8c490e3c391826d1e84fc85d44678/kadas/gui/catalog/kadasarcgisportalcatalogprovider.cpp#L119

Can we assert here that the &num Parameter never falls to 0?

I've got the problem here in Kadas that this value actually falls to 0 and the Catalog loads in an endless loop.

With a default value of 100 we should be good, that's the AGS max pagination value.

Here some estract of the endless loop in log:

warning: o/kadas/app/kadasapplication.cpp:2156 : (injectAuthToken) [76ms] injectAuthToken: got url https://npi.adr.admin.ch/arcgis/sharing/rest/search?f=pjson&q=tags%3A%22milcatalog%3A*%22+AND+%28type%3Awms+OR+type%3Awmts+OR+type%3A%22Map Service%22%29&lang=FR&timestamp=1643191752&start=0**&num=0**
warning: o/kadas/app/kadasapplication.cpp:2161 : (injectAuthToken) [33ms] injectAuthToken: got cookie TS01b6744a=0160edcfc79243ef8aa246680fc7db657c155ba4e0be9ea0cbc90ed82a85a9297489155a1701813244839e5618bb30eff4e78a233a; domain=npi.adr.admin.ch; path=/ for url https://npi.adr.admin.ch/arcgis/sharing/rest/search?f=pjson&q=tags%3A%22milcatalog%3A*%22+AND+%28type%3Awms+OR+type%3Awmts+OR+type%3A%22Map Service%22%29&lang=FR&timestamp=1643191752&start=0**&num=0**
warning: o/kadas/app/kadasapplication.cpp:288 : (operator()) [44ms] Network request: https://npi.adr.admin.ch/arcgis/sharing/rest/search?f=pjson&q=tags%3A%22milcatalog%3A*%22+AND+%28type%3Awms+OR+type%3Awmts+OR+type%3A%22Map Service%22%29&lang=FR&timestamp=1643191752&start=0**&num=0**

**Comment by manisandro** [comment]
Should be fixed with 4684e966d7208b79874aa235ad02642ca6fb287d
