### ISSUE TITLE
OpenSSL

### ISSUE THREAD

**Issue by bernspi** [kadas-albireo/kadas-albireo2#28]
Hello Sandro

Is the OpenSSL Vulnerability Issue (https://www.openssl.org/news/vulnerabilities.html) fixed in this repo? We had reports from our colleagues from austria that there is still an old OpenSSL Library in use here. Could you check please. 

Thanks a lot!
Regards 
Bernard

**Comment by manisandro** [comment]
Hi Bernard, I've now build [mingw-openssl-3.0.7-1.fc38](https://koji.fedoraproject.org/koji/buildinfo?buildID=2093901). It will take a couple of days for it to propagate to the repositories for the kadas CI build, but I can already manually produce updated builds if desired.

**Comment by bernspi** [comment]
Thanks alot! That's fine, no need to force a manual update.
