### ISSUE TITLE
Missing example project

### ISSUE THREAD

**Issue by tgdbepe4** [kadas-albireo/kadas-albireo2#4]
I learned some hours ago that the important DHM 2D and 3D files are not available for public in the Windows version. 

I tried in the following to use SRTM DHM data as well as the DTM from the canton Zurich, https://are.zh.ch/internet/baudirektion/are/de/aktuell/mitteilungen/gis/2015/hoehendatenzh.html which is available to the public and the OSM data provided from Terrestris https://www.terrestris.de/openstreetmap-wms/ but I failed to use it. The software was declared at the Fossgis2020 as an easy to use tool.

I strongly recommend to provide a running project file which use such open data to show that this is possible and that it has no local limitations to Switzerland and it's Army.

Peter

**Comment by manisandro** [comment]
Another sample project was added [1], using [2].

[1] https://github.com/kadas-albireo/kadas-albireo2/blob/master/packaging/files/project_templates/Online/CH%20(Online).qgz
[2] https://opendata.swiss/de/dataset/das-digitale-hohenmodell-der-schweiz-mit-einer-maschenweite-von-200-m
