### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by tgdbepe4** [kadas-albireo/kadas-albireo2#5]
Hi

I downloaded the last version of kadas and the demo as well but the software works still not as expected. In the analysis part the distance tool shows very strange values and the sheds are also not working. Please check the video on https://www.mycloud.ch/s/S00D795708B13A7F0DE6DC92816D1B047201EE5FFC2 which show what I have performed.

Regards, Peter

**Comment by manisandro** [comment]
Thanks, this a problem with the latest CI build problem, the QGIS build was built using a different version of proj than the KADAS build. A new QGIS build is running now, a new KADAS build will be triggered afterwards.

**Comment by manisandro** [comment]
Latest CI build should work.
