### ISSUE TITLE
Protocol info to small

### ISSUE THREAD

**Issue by tgdbepe4** [kadas-albireo/kadas-albireo2#6]
If something goes wrong a small  text line will be displayed on top but reading of this is more or less impossible. How can I made the Protocol visible?

**Comment by manisandro** [comment]
Could you give a better explanation please?

**Comment by tgdbepe4** [comment]
I mean this small field.
![grafik](https://user-images.githubusercontent.com/46052442/77394241-22d78a00-6d9f-11ea-92f8-7ad62e583ff8.png)

**Comment by manisandro** [comment]
You can press the pause button on the left to have more time to read the message.
