### ISSUE TITLE
Altitude info not working

### ISSUE THREAD

**Issue by tgdbepe4** [kadas-albireo/kadas-albireo2#7]
On the status line at the bottom of the screen information about coordinates from the mouse position is displayed and also the Altitude of it. The coordinates are correct but it shows no value or strange altitude information..
![image](https://user-images.githubusercontent.com/46052442/77366105-98b80300-6d57-11ea-8fc2-4d49aeca4270.png)

**Comment by manisandro** [comment]
Actually it's just the text cut off, for some reason the text inside the coordinate and height display fields is much too large.

**Comment by tgdbepe4** [comment]
Will this be corrected?

**Comment by manisandro** [comment]
Fixed in 6a29a99544c0d8601df922b678aa80da54aec3a2
