### ISSUE TITLE
Mixed coordinate system in different layers, no result

### ISSUE THREAD

**Issue by tgdbepe4** [kadas-albireo/kadas-albireo2#9]
I have a map layer in Pseudo Mercantor and a DHM Layer in LV03. The DHM Layer ist set as Altitude layer. I try to produce the hillshade (neigung). A new layer is produced but no way to made it visible.

![grafik](https://user-images.githubusercontent.com/46052442/77395592-33d5ca80-6da2-11ea-95e4-2f9b1304cdac.png)

**Comment by manisandro** [comment]
Can you attach the project?

**Comment by tgdbepe4** [comment]
Again I made a video, https://www.mycloud.ch/s/S00D795708B13A7F0DE6DC92816D1B047201EE5FFC2
Peter

**Comment by tgdbepe4** [comment]
Corrected now the right video. Sorry

**Comment by manisandro** [comment]
Cause was the projection for the output file being set equal to the projection of the input file, as returned directly by GDAL, which in this case was an invalid projection.

As per https://github.com/kadas-albireo/kadas-albireo2/commit/c40ac6df4c53113cd0debabb27902b4364d476af, the projection of the heightmap as selected in the layer properties is used.
